version: "3"
services:
  whistlepost:
    image: "micronode/whistlepost:1.2.3-develop-SNAPSHOT"
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Dsling.run.modes=dev
    volumes:
      - ./theme/app:/wp/apps/wnews:ro
      - ./assets:/wp/assets/wnews:ro
      - ./content:/wp/content/wnews:ro

  autoheal:
    restart: always
    image: willfarrell/autoheal
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
