---
label: Product
hide_body: true
fields:
- name: advanced_configuration
  type: boolean
  label: Advanced Configuration
  description: Show advanced configuration settings.
- name: sling:resourceType
  type: text
  config:
    required: true
  label: Resource Type
  description: Default resource type used to render page content.
  showOnly:
    field: advanced_configuration
    value: true
  default: wp/page/product
- name: thing
  type: include
  config: {}
  template: thing
  label: Thing
- name: category
  type: select
  default: []
  config:
    required: false
    options: []
    source:
      type: pages
      section: categories
      file: 
      path: 
  label: Category
